name: LemonLib
version: '${project.version}'
main: me.lemonypancakes.lemonlib.LemonLib
api-version: 1.17
load: STARTUP
softdepend:
  - PacketWrapper
  - ProtocolLib
authors: [ LemonyPancakes ]
description: A collection of libraries.
